CREATE TYPE "CurrencyKind" AS ENUM ('FIAT', 'STABLECOIN');

ALTER TABLE "Currency"
ADD COLUMN "kind" "CurrencyKind" NOT NULL DEFAULT 'FIAT',
ADD COLUMN "decimals" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN "settlementNetworks" JSONB NOT NULL DEFAULT '[]',
ALTER COLUMN "rate" TYPE DECIMAL(20,8);

ALTER TABLE "User" ALTER COLUMN "credits" TYPE DECIMAL(20,8);
ALTER TABLE "Product" ALTER COLUMN "affiliateCommissionValue" TYPE DECIMAL(20,8);
ALTER TABLE "Product" ALTER COLUMN "meteredUnitPrice" TYPE DECIMAL(20,8);
ALTER TABLE "ProductPrice" ALTER COLUMN "price" TYPE DECIMAL(20,8);
ALTER TABLE "ProductPrice" ALTER COLUMN "setupFee" TYPE DECIMAL(20,8);
ALTER TABLE "ConfigOptionValue" ALTER COLUMN "price" TYPE DECIMAL(20,8);
ALTER TABLE "Order" ALTER COLUMN "subtotal" TYPE DECIMAL(20,8);
ALTER TABLE "Order" ALTER COLUMN "discount" TYPE DECIMAL(20,8);
ALTER TABLE "Order" ALTER COLUMN "tax" TYPE DECIMAL(20,8);
ALTER TABLE "Order" ALTER COLUMN "total" TYPE DECIMAL(20,8);
ALTER TABLE "OrderItem" ALTER COLUMN "unitPrice" TYPE DECIMAL(20,8);
ALTER TABLE "OrderItem" ALTER COLUMN "setupFee" TYPE DECIMAL(20,8);
ALTER TABLE "Service" ALTER COLUMN "price" TYPE DECIMAL(20,8);
ALTER TABLE "Invoice" ALTER COLUMN "subtotal" TYPE DECIMAL(20,8);
ALTER TABLE "Invoice" ALTER COLUMN "discount" TYPE DECIMAL(20,8);
ALTER TABLE "Invoice" ALTER COLUMN "tax" TYPE DECIMAL(20,8);
ALTER TABLE "Invoice" ALTER COLUMN "total" TYPE DECIMAL(20,8);
ALTER TABLE "InvoiceItem" ALTER COLUMN "unitPrice" TYPE DECIMAL(20,8);
ALTER TABLE "Payment" ALTER COLUMN "amount" TYPE DECIMAL(20,8);
ALTER TABLE "Coupon" ALTER COLUMN "value" TYPE DECIMAL(20,8);
ALTER TABLE "Quote" ALTER COLUMN "subtotal" TYPE DECIMAL(20,8);
ALTER TABLE "Quote" ALTER COLUMN "tax" TYPE DECIMAL(20,8);
ALTER TABLE "Quote" ALTER COLUMN "total" TYPE DECIMAL(20,8);
ALTER TABLE "QuoteItem" ALTER COLUMN "unitPrice" TYPE DECIMAL(20,8);
ALTER TABLE "Affiliate" ALTER COLUMN "balance" TYPE DECIMAL(20,8);
ALTER TABLE "Affiliate" ALTER COLUMN "totalEarned" TYPE DECIMAL(20,8);
ALTER TABLE "AffiliateCommission" ALTER COLUMN "amount" TYPE DECIMAL(20,8);
